# Site settings
title: The Stuff Unseen # site title
description: >
  See the unseen things in mind and everything in the universe.
lang: en-US # default lang
timezone: Asia/Jakarta # set your timezone
image: assets/img/avatar.png # This image used for Open Graph more info https://ogp.me/
repo: # site repo [optional]
mode: light # default theme "dark" | "light"
logo: /assets/img/avatar.png

# Profile settings
author:
  name: Tiểu Núi # author name
  bio: "" # author bio
  username: tieunui # general username
  github: sonkd # github username
  twitter: "" # twitter username
  facebook: "" # facebook username
  email: sonkdbk@gmail.com
  avatar: "" # author avatar

# URL settings
url: "https://stuffunseen.com" #
baseurl: "" # baseurl must be a string, empty if not used
permalink: /:title/
# permalink: /:year/:month/:title.html
google_analytics: G-S9NVMFYQ7Y # Google Tag Manager
fb_appid:

# Homepage limit posts
number_of_posts: 5

# Produces a cleaner folder structure when using categories
# Collection setting
collections_dir: my_collections
collections:
  stuff:
    output: true
    permalink: /stuff/:name/
  articles:
    output: true
    permalink: /article/:name/
  quotes:
    output: true
    permalink: /quote/:name/
  researches:
    output: true
    permalink: /research/:name/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM

# Default front matter ==> dùng jekyll-archives thay thế
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: true
  - scope:
      path: "_stuff"
      type: "stuff"
    values:
      permalink: /:name/
      layout: stuff-page

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified: ""
    tags: []
    description: ""
  draft_default_front_matter:
    modified: ""
    tags: []
    description: ""

# Show category
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    year: year-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/categories/:name/"
  # Add this line to include all collections in archives
  collections:
    - posts
    - stuff
    - articles
    - quotes
    - researches

# Build settings
# theme: klise
sass:
  sass_dir: _sass
  style: compressed

include:
  - _redirects
  - .htaccess
  - _pages

gems:
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 11
  collections:
    - posts
    - stuff
    - articles
    - quotes
    - researches
  permalink: "/page/:num/"
  title: ":title - page :num of :max"
  # sort_field: 'date'
  sort_field: "title"
  sort_reverse: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-postcss
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate-v2

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
  - notion_sync.py