# Site settings
title: The Stuff Unseen # site title
description: >
  See the unseen things in mind and everything in the universe.
lang: en-US # default lang
timezone: Asia/Jakarta # set your timezone
image: assets/img/avatar.png # This image used for Open Graph more info https://ogp.me/
repo: # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: The Stuff Unseen # author name
  bio: >- # tell to the world
    The seen is the changing, the unseen is the unchanging.
    <a href="https://www.azquotes.com/quote/777679?ref=unseen" target="_blank" rel="noopener">Plato</a>.
  username: tieunui # general username
  github: sonkd # github username
  twitter: # twitter username
  facebook: # facebook username
  email:  sonkdbk@gmail.com
  avatar: /assets/img/avatar.png # change with your own avatar

# URL settings
url: "https://stuffunseen.com" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections_dir: collections
collections:
  posts:
    output: true
  category:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: true
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  
# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 9

# Show category
jekyll-archives:
  enabled:
    #- categories
    - year
    - tags
  layouts:
    year: year-archive
    #category: category-archive
    tag: tag-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    #category: '/category/:name/'

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess
  - _pages

gems:
  - jekyll-paginate-v2

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Produces a cleaner folder structure when using categories
# permalink: /:year/:month/:title.html

# Pagination Settings
pagination:
  enabled: true
  per_page: 12
  offset: 0
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate-v2