import { c as createComponent, m as maybeRenderHead, f as renderScript, a as renderTemplate } from './astro/server_CwOJRIjy.mjs';
import 'piccolore';
import 'clsx';
/* empty css                         */

const $$StuffOverlay = createComponent(async ($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<div id="stuff-overlay" class="stuff-overlay hidden" aria-hidden="true" data-astro-cid-gchk47a6> <div class="overlay-backdrop" data-close="true" data-astro-cid-gchk47a6></div> <aside class="overlay-side overlay-refs" data-astro-cid-gchk47a6> <div class="panel-label" data-astro-cid-gchk47a6>REFS · LIÊN QUAN</div> <ul id="stuff-refs" data-astro-cid-gchk47a6></ul> </aside> <section class="overlay-card" id="overlay-card" role="button" tabindex="0" aria-label="Lật card · Flip card" data-astro-cid-gchk47a6> <div class="flip-hint hidden" id="flip-hint" data-astro-cid-gchk47a6>Bấm để lật · Click to flip</div> <div class="card-inner" id="card-inner" data-astro-cid-gchk47a6> <div class="card-face card-front" id="card-front" data-astro-cid-gchk47a6> <div class="card-top" data-astro-cid-gchk47a6> <span class="card-icon" id="stuff-icon-front" data-astro-cid-gchk47a6></span> <span class="card-name" id="stuff-title-front" data-astro-cid-gchk47a6></span> </div> <div class="card-cats" id="stuff-cats" data-astro-cid-gchk47a6></div> <div class="card-stage" id="stuff-stage-front" data-astro-cid-gchk47a6></div> <p class="card-text" id="stuff-front" data-astro-cid-gchk47a6></p> <div class="card-footer" data-astro-cid-gchk47a6> <button id="overlay-close" type="button" data-astro-cid-gchk47a6>CLOSE · ĐÓNG</button> <button id="overlay-share" type="button" data-astro-cid-gchk47a6>SHARE · CHIA SẺ</button> </div> </div> <div class="card-face card-back" id="card-back" data-astro-cid-gchk47a6> <div class="back-label" data-astro-cid-gchk47a6>BACK · MẶT SAU</div> <div class="card-top" data-astro-cid-gchk47a6> <span class="card-icon" id="stuff-icon-back" data-astro-cid-gchk47a6></span> <span class="card-name" id="stuff-title-back" data-astro-cid-gchk47a6></span> </div> <div class="card-body" id="stuff-body" data-astro-cid-gchk47a6></div> <div class="card-stage" id="stuff-stage-back" data-astro-cid-gchk47a6></div> <div class="card-footer" data-astro-cid-gchk47a6> <button id="overlay-close-back" type="button" data-astro-cid-gchk47a6>CLOSE · ĐÓNG</button> </div> </div> </div> </section> <aside class="overlay-side overlay-links" data-astro-cid-gchk47a6> <div class="panel-label" data-astro-cid-gchk47a6>LINKS</div> <ul id="stuff-links" data-astro-cid-gchk47a6></ul> </aside> </div> ${renderScript($$result, "/sessions/funny-exciting-shannon/mnt/theunseen/src/components/map/StuffOverlay.astro?astro&type=script&index=0&lang.ts")} `;
}, "/sessions/funny-exciting-shannon/mnt/theunseen/src/components/map/StuffOverlay.astro", void 0);

export { $$StuffOverlay as $ };
